version: '3.8'

services:

  notes-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: notes-app
    container_name: notes-app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://172.17.0.1:27017/notes
    depends_on:
      - mongo-setup

  mongo-setup:
    container_name: mongo-setup-container
    image: mongo:5
    restart: no
    volumes:
      - ./mongo-setup.sh:/scripts/mongo-setup.sh
    entrypoint: [ "/scripts/mongo-setup.sh" ]
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: notes
    volumes:
      - mongodb_data:/data/db
    entrypoint: ["mongod", "--bind_ip_all", "--replSet", "rs0"]

volumes:
  mongodb_data: